import { DecorationItem } from "./types";

export const DECORATIONS_CATALOG: DecorationItem[] = [
  {
    id: "tree-1",
    name: "산소 듬뿍 느티나무",
    category: "nature",
    price: 30,
    emoji: "🌳",
    description: "주변의 이산화탄소를 흡수하고 맑은 산소를 공급하는 친환경 필수 나무입니다.",
    ecoScoreBonus: 10,
  },
  {
    id: "flower-1",
    name: "생태 정원 화단",
    category: "nature",
    price: 15,
    emoji: "🌸",
    description: "꿀벌과 나비를 다시 부르고 토양을 건강하게 만드는 예쁜 꽃밭입니다.",
    ecoScoreBonus: 5,
  },
  {
    id: "solar-1",
    name: "지붕 태양광 패널",
    category: "energy",
    price: 60,
    emoji: "☀️",
    description: "햇빛으로 무공해 친환경 전력을 상시 생산하여 화석 연료 의존도를 낮춥니다.",
    ecoScoreBonus: 18,
  },
  {
    id: "wind-1",
    name: "친환경 풍력 발전기",
    category: "energy",
    price: 100,
    emoji: "🌀",
    description: "언덕에서 돌아가는 바람개비 동력으로 에너지를 모으는 고효율 친환경 발전기입니다.",
    ecoScoreBonus: 30,
  },
  {
    id: "waste-1",
    name: "자원순환 분리배출함",
    category: "waste",
    price: 20,
    emoji: "♻️",
    description: "페트병과 캔을 철저히 모아 자원 재탄생에 이바지하는 현대적 수거함입니다.",
    ecoScoreBonus: 8,
  },
  {
    id: "house-1",
    name: "저탄소 에코 빌라",
    category: "living",
    price: 150,
    emoji: "🏡",
    description: "천연 목재와 극대화된 단열 설계를 활용한 탄소 배출 제로형 명품 주택입니다.",
    ecoScoreBonus: 40,
  },
  {
    id: "bike-1",
    name: "공유 자전거 보관소",
    category: "transport",
    price: 45,
    emoji: "🚲",
    description: "가까운 거리는 대중교통이나 자동차 대신 무탄소 자전거로 통행하도록 유도합니다.",
    ecoScoreBonus: 15,
  },
  {
    id: "compost-1",
    name: "에코 낙엽 퇴비함",
    category: "waste",
    price: 25,
    emoji: "📦",
    description: "음식물 잔여물을 친환경 퇴비로 발효시켜 유기농 식물의 성장을 활성화합니다.",
    ecoScoreBonus: 8,
  },
  {
    id: "water-1",
    name: "빗물 저장소",
    category: "living",
    price: 50,
    emoji: "🛢️",
    description: "지붕에서 내리는 빗물을 정화, 저수하여 에코 정원에 수자원을 지속 가능하게 공급합니다.",
    ecoScoreBonus: 15,
  }
];
